# Generated by Django 4.0.3 on 2022-04-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjectApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Major',
        ),
    ]
